version: "3.7"

services:
  item-db:
    image: mongo:3
    volumes:
      - app-db:/data/lib

  item-app:
    image: askus/item-app:v1
    ports:
      - 80:8080
    volumes:
      - ./:/app
    depends_on:
      - item-db
    build: .

volumes:
  app-db:

